# Generated by Django 5.2 on 2025-05-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address_line_1",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(max_length=20),
        ),
    ]
